[package]
name = "ordiseq"
description = "A MIDI sequencer library"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/EnigmaCurry/ordiseq"
homepage = "https://github.com/EnigmaCurry/ordiseq"
license = "MIT"
keywords = []
readme = "README.md"
documentation = "https://docs.rs/ordiseq"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage,coverage_nightly)'] }

[dependencies]
dirs = "6.0.0"
env_logger = "0.11.8"
log = "0.4.29"
## Use stable git repo until kord >0.7.1 is released
kord = { git = "https://github.com/EnigmaCurry/kord.git" }
midir = "0.10.3"
midly = "0.5.3"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34"
strum = { version = "0.27.2", features = ["derive"] }
thiserror = "2.0.17"

[dev-dependencies]
shell-words = "1.1.1"
clap = "4.5.53"
clap_complete = "4.5.61"

[build-dependencies]
clap = "4.5.53"
clap_complete = "4.5.61"
dirs = "6.0.0"
